version: 3
endpoint: http://localhost:8080
admin_secret:
insecure_skip_tls_verify: false
certificate_authority: 
access_key: #deprecated
api_paths:
  query: 	v1/query
  graphql: v1/graphql
  config: v1alpha1/config
  pg_dump: v1alpha1/pg_dump
  version: v1/version
metadata_directory: 	migrations
migrations_directory:
seeds_directory:
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
  codegen:
    framework:
    output_dir:
    uri: